name: CI

on:
  push:
    branches:
      - "2021/groovy"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setting up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Test with Gradle
        run: ./gradlew check